export const nav = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Projects", href: "/#projects" },
  { label: "Contact", href: "/#contact" },
  // { label: "Work", href: "#work" },
  // { label: "Skills", href: "#skills" },
  // { label: "Experience", href: "#experience" },

];

export const projects = [
  {
    num: "01",
    slug: "lavido-auto-parts",
    type: "E-Commerce · 2025",
    title: "Lavido Auto Parts",
    desc: "Full-stack ecommerce platform for a Johannesburg auto parts retailer. Shop with advanced filtering, multi-step checkout, workshop booking, and a customer dashboard — built production-ready on Next.js 15 App Router.",
    longDesc: "Lavido Auto Parts is a premium ecommerce platform for a Vosloorus, Johannesburg-based auto parts retailer. The brief was to build a professional, scalable storefront that could compete with national retailers — clean enough to earn trust from first-time visitors, functional enough to handle real purchase flows. I architected and built the entire frontend on Next.js 15 App Router with TypeScript, implementing a full shop experience: filterable product listings, detailed product pages with specs and compatibility tables, a three-step checkout (delivery, shipping, payment), and a Zustand-powered cart that persists across sessions. Beyond the shop, the platform includes a workshop booking system, a customer account dashboard, a blog, and full authentication screens — everything a growing retail business needs to operate digitally from day one.",
    features: [
      "Shop listing with sidebar filters — brand, category, price range, and stock status",
      "Product detail pages with specification tables and part compatibility information",
      "3-step checkout flow — Delivery → Shipping → Payment → Order confirmation",
      "Zustand cart with localStorage persistence — survives page refresh and navigation",
      "Workshop booking form with service type, date, and time slot selection",
      "Customer dashboard — order history, saved addresses, profile, and settings",
      "Auth system — login, register, and Google/Facebook social sign-in screens",
      "Custom design system using Playfair Display, Space Grotesk, and Inter typefaces",
    ],
    stat: "Next.js 15 App Router · 8 route sections · full design system",
    chips: ["Next.js 15", "TypeScript", "Tailwind CSS", "Zustand"],
    tealChips: ["App Router", "Lucide React"],
    liveHref: "https://www.lavidoautoparts.co.za/",
    color: "linear-gradient(135deg, #1a0e04 0%, #2d1a08 40%, #1a1005 70%, #0f0a02 100%)",
    image: "/lavido-auto-parts.png",
  },
  {
    num: "02",
    slug: "africonnect-solutions",
    type: "Internal Tool · POS · 2024",
    title: "Africonnect Solutions Portal",
    desc: "Full-stack POS and operations portal built for an SME client. JWT-authenticated, real-time sales dashboard, multi-line-item sale builder, date-range reporting, and Excel export — on Next.js 16 App Router, used by staff daily.",
    longDesc: "Most off-the-shelf POS tools are either overpriced for small operators or so generic they require weeks of configuration before a sale can be recorded. Africonnect Solutions needed something different — purpose-built for their workflow, fast to learn, and reliable enough to run the front desk. I built the full stack: a Node.js/Express REST API backed by PostgreSQL on Neon, and a Next.js 16 App Router frontend on top of it. The dashboard gives staff an immediate read on today's revenue, transaction count, and average sale value alongside a live Recharts flow chart. The sale builder lets operators select from a live service catalogue, add multiple line items, assign the responsible employee, and choose a payment method before a running total updates in real time. Sales can be soft-deleted with a confirm dialog and reviewed in a dedicated audit archive — nothing is ever lost without a trace. A reports module pulls revenue summaries across custom date ranges, and a one-click Excel export via SheetJS handles end-of-day reconciliation. Because the tool is used by non-technical staff, I built an in-app help centre documenting every section — the goal was zero external support needed from day one.",
    features: [
      "Real-time dashboard — daily revenue, transaction count, average sale value, and a live Recharts flow chart",
      "Multi-line-item sale builder with service catalogue, quantity, unit pricing, and a live running total",
      "Payment method selection per transaction — Cash, Card, and EFT, colour-coded in the sales table",
      "Employee assignment on each sale for accountability and commission visibility",
      "Sales history with date filtering, global TanStack Table search, and per-row soft-delete with confirm dialog",
      "Excel export of any day's sales to .xlsx via SheetJS — one click from the toolbar",
      "Soft-delete audit trail — deleted sales are archived, not destroyed, with a dedicated review page",
      "Revenue reports with custom date range selection and Recharts visualisations",
      "In-app help centre covering every section — built for non-technical operators from day one",
      "JWT auth via Zustand persist — sessions survive refresh, every API call auto-attaches Bearer token",
      "Responsive layout with collapsible bottom nav on mobile — usable from counter and phone",
    ],
    stat: "Internal tool · used by staff daily · full-stack · Excel export",
    chips: ["Next.js 16", "TypeScript", "Tailwind CSS v4", "Node.js", "Express"],
    tealChips: ["TanStack Table", "Recharts", "Zustand v5", "PostgreSQL"],
    liveHref: "#",
    isPrivate: true,
    color: "linear-gradient(135deg, #051a0e 0%, #0a3020 40%, #083a25 70%, #041208 100%)",
    images: [
      "/africonnect-dashboard.png",
      "/africonnect-new-sale.png",
      "/africonnect-login.png",
      "/africonnect-help.png",
    ],
  },
  // {
  //   num: "03",
  //   slug: "pulse-hr",
  //   type: "SaaS · 2023",
  //   title: "PulseHR",
  //   desc: "HR management tool for South African SMEs. Leave tracking, payroll snapshots, document management. Designed to be picked up without a manual — which is the hardest thing to actually pull off.",
  //   longDesc: "Most HR software is built for large enterprises with dedicated HR teams. PulseHR was built for the 50-person company where the HR 'department' is one person also doing finance. The goal was zero training time — an employee should be able to apply for leave on their first day without asking anyone how. I built the full frontend with a heavy focus on progressive disclosure: simple on the surface, powerful underneath. The charting layer (Recharts) visualises headcount trends, leave patterns, and payroll snapshots in a way that actually informs decisions rather than just looking impressive.",
  //   features: [
  //     "Leave management with multi-level approval chains",
  //     "Payroll snapshot dashboard with month-on-month comparison",
  //     "Document storage and e-sign workflow for employment contracts",
  //     "Employee self-service portal — no HR intervention for routine requests",
  //     "Recharts-powered analytics with exportable reports",
  //     "Animated UI transitions via Framer Motion for a polished feel",
  //   ],
  //   stat: "Used daily by 14 companies across Gauteng",
  //   chips: ["React", "Firebase", "Recharts"],
  //   tealChips: ["Framer Motion"],
  //   liveHref: "#",
  //   color: "linear-gradient(135deg, #030f2a 0%, #0a1f45 40%, #0e2858 70%, #040d20 100%)",
  // },
  // {
  //   num: "04",
  //   slug: "ndaba-creative",
  //   type: "Agency site · 2023",
  //   title: "Ndaba Creative",
  //   desc: "Portfolio site for a Joburg creative studio. Heavy on motion, precise on performance. Three-week build. They won two clients from the contact form in the first month, which is always a good sign.",
  //   longDesc: "Ndaba Creative came in with a brief that said 'we want something that feels alive.' That's the kind of brief that can go badly wrong. The challenge was building something heavily motion-driven without tanking performance — a 10-second load time would undermine the whole impression they were trying to create. I used GSAP for all motion work, with careful attention to which animations were compositor-only (transform, opacity) and which would trigger repaints. The Sanity CMS integration lets the team update case studies, add clients, and change hero content without touching code. The contact form conversion rate in month one justified the whole budget.",
  //   features: [
  //     "GSAP-powered scroll animations — compositor-only for 60fps performance",
  //     "Sanity CMS for content management with live preview",
  //     "Custom cursor and hover interactions",
  //     "Case study pages with full-bleed image layouts",
  //     "Contact form with Resend email integration",
  //     "Sub-2 second load time despite animation-heavy design",
  //   ],
  //   stat: "Built and deployed in 21 days",
  //   chips: ["Vue.js", "GSAP", "Sanity CMS"],
  //   tealChips: ["Vercel"],
  //   liveHref: "#",
  //   color: "linear-gradient(135deg, #120828 0%, #2a1060 40%, #1a0848 70%, #080318 100%)",
  // },
  // {
  //   num: "05",
  //   slug: "township-finder",
  //   type: "Side project · Ongoing",
  //   title: "Township Finder",
  //   desc: "Local services directory for township economies — built offline-first because data costs money and not everyone has consistent signal. Still figuring out the business model, but people use it, which counts for a lot.",
  //   longDesc: "Township Finder exists because Google Maps doesn't know about Mama Thandi's hair salon that's been operating out of the same container for eight years. Informal businesses in township economies are largely invisible to digital platforms, but they're the economic backbone of millions of South Africans. The technical constraints were the brief: assume the user has a cheap Android phone, an intermittent data connection, and is not going to wait for a spinner. I built it as a PWA with full offline capability — service workers cache the local directory data and IndexedDB handles offline search. It works on 2G. It works with no signal at all once loaded. No login required, because every extra step loses users.",
  //   features: [
  //     "Full offline support via Service Workers and IndexedDB",
  //     "Installable PWA — works like a native app on Android",
  //     "Functional on 2G — total initial payload under 80kb",
  //     "Location-based search with fallback to manual area selection",
  //     "Business submission form for owners to add themselves",
  //     "No account required for browsing — zero friction",
  //   ],
  //   stat: "PWA · works on 2G · no login required",
  //   chips: ["React"],
  //   tealChips: ["Service Workers", "IndexedDB"],
  //   liveHref: "#",
  //   color: "linear-gradient(135deg, #1a0e04 0%, #321a08 40%, #3d2212 70%, #120802 100%)",
  // },
];

export const skillGroups = [
  {
    teal: false,
    label: "Languages",
    chips: ["JavaScript ES6+", "TypeScript", "HTML5", "CSS3 / SCSS", "Java"],
  },
  {
    teal: false,
    label: "Frameworks",
    chips: ["React", "Next.js", "Tailwind CSS", "Springboot"],
  },
  {
    teal: true,
    label: "Tooling & Infra",
    chips: ["Git / GitHub", "Vite", "Firebase", "Supabase", "Vercel"],
  },
  {
    teal: true,
    label: "Design & Process",
    chips: ["Figma"],
  },
];

export const experience = [
  {
    years: "Feb 2023 — Present",
    role: "Frontend Developer",
    company: "Telkom · Contract · Centurion, Hybrid",
    desc: "Building internal and consumer-facing web applications within an agile team at one of South Africa's largest telecoms. Work spans the full frontend delivery cycle — developing UI from designs, integrating REST APIs via Spring Boot, and shipping HTML email templates with VML for Outlook compatibility. Also responsible for data layer implementation and Google Analytics event tracking.",
    chips: ["React", "Tailwind CSS", "JavaScript", "jQuery", "HTML5"],
    tealChips: ["Spring Boot", "Google Analytics"],
  },
  {
    years: "Feb 2021 — Jan 2023",
    role: "Software Developer Intern",
    company: "Telkom · Remote · South Africa",
    desc: "Full-stack development focused on migrating legacy applications to modern stacks. Rebuilt old systems using React and Node.js, and gained hands-on exposure to Java-based backends through Spring Boot, Maven, and enterprise development practices.",
    chips: ["React", "Node.js", "Java", "Spring Boot"],
    tealChips: ["Maven"],
  },
  {
    years: "Nov 2020 — Jan 2021",
    role: "Full-stack Developer Intern",
    company: "Zaio · South Africa",
    desc: "Upskilled in the MERN stack in preparation to become a full-stack development tutor for Zaio students. Built projects across the stack and developed the ability to explain technical concepts clearly — a skill that's made me a better collaborator ever since.",
    chips: ["MongoDB", "Express", "React", "Node.js"],
    tealChips: ["HTML5"],
  },
];

export const facts = [
  { label: "Based in", value: "Johannesburg, SA" },
  { label: "Experience", value: "5+ years" },
  { label: "Availability", value: "Open to work", teal: true },
  { label: "Focus", value: "Next.js · Springboot" },
  // { label: "Also does", value: "Design systems, audits" },
  // { label: "Languages", value: "English, isiZulu" },
];

export const contact = {
  email: "hello@xolanimgube.co.za",
  links: [
    { label: "LinkedIn", href: "https://www.linkedin.com/in/xolani-mgube-b50974185/", display: "linkedin.com/in/xolanimgube" },
    { label: "GitHub",   href: "https://github.com/XolaniMgube", display: "github.com/xolanimgube" },
    { label: "Location", href: null, display: "Johannesburg, Gauteng — SA" },
  ],
};

export const footerLinks = [
  { label: "GitHub",   href: "https://github.com/XolaniMgube" },
  { label: "LinkedIn", href: "https://www.linkedin.com/in/xolani-mgube-b50974185/" },
  // { label: "Twitter",  href: "#" },
  { label: "CV",       href: "/cv.pdf" },
];
